id: fa92257084d04b74b869f09151805ce9
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_325-The_Verses_of_Naga_King_Drum-v2
  language: bo
  author: ''
  volume: {}
